<?php


namespace Src\Enums;
use MyCLabs\Enum\Enum;

class INTERNAL_PAGES extends Enum
{
    CONST LANDING = 0;
    CONST TRANSCRIBE = 1;
    CONST JOB_LISTER = 2;
    CONST ADMIN_PANEL_INDEX = 3;

    CONST USERS = 5;
    CONST ACCOUNTS = 6;
    CONST ADMIN_TOOLS = 7;
    CONST BILLING_REPORTS = 8;
    CONST TYPIST_REPORTS = 9;
    CONST PACKAGES = 10;
    CONST PAYMENT = 11;
    CONST MANAGE_TYPISTS = 12;
    CONST MANAGE_USER_ACCESS = 13;
    CONST PAYMENT_DETAILS = 14;
    CONST JOB_UPLOAD = 404;


}